[build-system]
requires = [
    "setuptools >= 69.5.1",
    "wheel",
]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 80
skip-string-normalization = true
target-version = [ "py39" ]

[tool.pytest.ini_options]
testpaths = [ "tests" ]
